#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

APP_NAME="waygate"
INSTALL_DIR="/opt/waygate"
ENV_DEST="/etc/waygate.env"
SERVICE_PATH="/etc/systemd/system/waygate.service"
TMPFILES_PATH="/etc/tmpfiles.d/waygate.conf"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${WAYGATE_ENV_FILE:-}"
CLEANUP_ENV_FILE=""
AUTO_ENV_FILE=0
NO_START=0

CONFIG_KEYS=(
  WG_INTERFACE WG_PORT WG_SERVER_HOST WG_SERVER_NET WG_DEFAULT_DNS
  API_AUTH_TOKEN API_HOST API_PORT WG_PERSISTENT_KEEPALIVE
  WG_OUTBOUND_INTERFACE API_PUBLIC_BASE_URL ALLOW_INSECURE_HTTP
  API_ALLOWED_CIDRS API_DOCS_ENABLED
)

usage() {
  cat <<'EOF'
Usage: deploy/install.sh [options]

Build and install the native systemd service. Application configuration comes
from exported environment variables or --env-file.

Options:
  --env-file PATH       Read application variables from PATH.
  --source-dir PATH     Install from a source tree instead of the repository root.
  --no-start            Install files but do not enable or start the service.
  -h, --help            Show this help.

Required variables:
  WG_SERVER_HOST        Public WireGuard IP address or DNS name.
  API_AUTH_TOKEN        At least 32 random characters.

For a non-loopback API_HOST, API_ALLOWED_CIDRS is also required.
EOF
}

while (($#)); do
  case "$1" in
    --env-file)
      [[ $# -ge 2 ]] || { echo "--env-file requires a path" >&2; exit 2; }
      ENV_FILE="$2"
      shift 2
      ;;
    --source-dir)
      [[ $# -ge 2 ]] || { echo "--source-dir requires a path" >&2; exit 2; }
      SOURCE_DIR="$2"
      shift 2
      ;;
    --no-start)
      NO_START=1
      shift
      ;;
    --cleanup-env-file)
      [[ $# -ge 2 ]] || { echo "--cleanup-env-file requires a path" >&2; exit 2; }
      CLEANUP_ENV_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ((EUID != 0)); then
  if [[ -z "$ENV_FILE" ]]; then
    ENV_FILE="$(mktemp "${TMPDIR:-/tmp}/waygate-install-env.XXXXXX")"
    chmod 600 "$ENV_FILE"
    trap 'rm -f -- "$ENV_FILE"' EXIT
    AUTO_ENV_FILE=1
    for key in "${CONFIG_KEYS[@]}"; do
      if [[ -n ${!key+x} ]]; then
        printf '%s=%q\n' "$key" "${!key}" >> "$ENV_FILE"
      fi
    done
  fi
  sudo_args=("$0" --env-file "$ENV_FILE" --source-dir "$SOURCE_DIR")
  ((NO_START == 1)) && sudo_args+=(--no-start)
  ((AUTO_ENV_FILE == 1)) && sudo_args+=(--cleanup-env-file "$ENV_FILE")
  exec sudo "${sudo_args[@]}"
fi

if [[ -n "$ENV_FILE" ]]; then
  [[ -f "$ENV_FILE" ]] || { echo "Environment file not found: $ENV_FILE" >&2; exit 2; }
  set -a
  # The file is generated by this installer, the TUI, or cloud-init.
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

: "${WG_SERVER_HOST:?WG_SERVER_HOST is required}"
: "${API_AUTH_TOKEN:?API_AUTH_TOKEN is required}"

WG_INTERFACE="${WG_INTERFACE:-wg0}"
WG_PORT="${WG_PORT:-51820}"
WG_SERVER_NET="${WG_SERVER_NET:-10.8.0.0/24}"
WG_DEFAULT_DNS="${WG_DEFAULT_DNS:-1.1.1.1}"
API_HOST="${API_HOST:-127.0.0.1}"
API_PORT="${API_PORT:-8080}"
WG_PERSISTENT_KEEPALIVE="${WG_PERSISTENT_KEEPALIVE:-25}"
WG_OUTBOUND_INTERFACE="${WG_OUTBOUND_INTERFACE:-}"
API_PUBLIC_BASE_URL="${API_PUBLIC_BASE_URL:-}"
ALLOW_INSECURE_HTTP="${ALLOW_INSECURE_HTTP:-false}"
API_ALLOWED_CIDRS="${API_ALLOWED_CIDRS:-}"
API_DOCS_ENABLED="${API_DOCS_ENABLED:-false}"

(( ${#API_AUTH_TOKEN} >= 32 )) || { echo "API_AUTH_TOKEN must contain at least 32 characters" >&2; exit 2; }
if [[ "$API_HOST" != "127.0.0.1" && "$API_HOST" != "localhost" && "$API_HOST" != "::1" && -z "$API_ALLOWED_CIDRS" ]]; then
  echo "API_ALLOWED_CIDRS is required when API_HOST is non-loopback" >&2
  exit 2
fi

if [[ -z "$WG_OUTBOUND_INTERFACE" ]] && command -v ip >/dev/null 2>&1; then
  WG_OUTBOUND_INTERFACE="$(ip -4 route show default | awk 'NR == 1 { for (i = 1; i <= NF; i++) if ($i == "dev") { print $(i + 1); exit } }')"
fi

if command -v apt-get >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  export NEEDRESTART_MODE=a
  apt-get update
  if ! command -v python3.12 >/dev/null 2>&1; then
    apt-get install -y ca-certificates software-properties-common
    if ! apt-cache show python3.12 >/dev/null 2>&1; then
      add-apt-repository -y ppa:deadsnakes/ppa
      apt-get update
    fi
  fi
  apt-get install -y ca-certificates curl iproute2 iptables python3.12 python3.12-venv wireguard-tools
else
  command -v python3.12 >/dev/null 2>&1 || { echo "python3.12 is required on non-Debian systems" >&2; exit 1; }
  command -v wg >/dev/null 2>&1 || { echo "wireguard-tools is required" >&2; exit 1; }
  command -v iptables >/dev/null 2>&1 || { echo "iptables is required" >&2; exit 1; }
fi

[[ -d "$SOURCE_DIR" ]] || { echo "Source directory not found: $SOURCE_DIR" >&2; exit 2; }
[[ -f "$SOURCE_DIR/pyproject.toml" ]] || { echo "pyproject.toml not found in $SOURCE_DIR" >&2; exit 2; }
[[ -f "$SOURCE_DIR/requirements.lock" && -f "$SOURCE_DIR/requirements-build.lock" ]] || {
  echo "Hashed dependency lock files are required" >&2
  exit 2
}

WORK_DIR="$(mktemp -d /tmp/waygate-build.XXXXXX)"
cleanup() {
  rm -rf -- "$WORK_DIR"
  if [[ -n "$CLEANUP_ENV_FILE" ]]; then
    rm -f -- "$CLEANUP_ENV_FILE"
  fi
}
trap cleanup EXIT

# Archive first so re-running from /opt/waygate is safe.
tar -C "$SOURCE_DIR" \
  --exclude=.git --exclude=.env --exclude=.venv --exclude=.build-venv \
  --exclude=build --exclude=dist --exclude='__pycache__' \
  -cf "$WORK_DIR/source.tar" .

for service in "$APP_NAME.service" afterglow-wg-agent.service; do
  if systemctl list-unit-files "$service" >/dev/null 2>&1 && systemctl is-active --quiet "$service"; then
    systemctl stop "$service"
  fi
done
if systemctl is-active --quiet afterglow-wg-agent.service; then
  echo "legacy service is still active after stop" >&2
  exit 1
fi
if [[ -x "$SOURCE_DIR/deploy/migrate-legacy.sh" ]]; then
  "$SOURCE_DIR/deploy/migrate-legacy.sh"
fi
rm -rf -- "$INSTALL_DIR"
install -d -m 0755 -o root -g root "$INSTALL_DIR"
tar -C "$INSTALL_DIR" -xf "$WORK_DIR/source.tar"

python3.12 -m venv "$WORK_DIR/build-venv"
"$WORK_DIR/build-venv/bin/python" -m pip install --require-hashes -r "$INSTALL_DIR/requirements-build.lock"
mkdir -p "$WORK_DIR/wheel"
"$WORK_DIR/build-venv/bin/python" -m pip wheel --no-build-isolation --no-deps "$INSTALL_DIR" -w "$WORK_DIR/wheel"

python3.12 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/python" -m pip install --require-hashes -r "$INSTALL_DIR/requirements.lock"
wheel_path=""
for candidate in "$WORK_DIR"/wheel/*.whl; do
  if [[ -f "$candidate" ]]; then
    wheel_path="$candidate"
    break
  fi
done
[[ -n "$wheel_path" ]] || { echo "Wheel build produced no artifact" >&2; exit 1; }
"$INSTALL_DIR/.venv/bin/python" -m pip install --no-deps "$wheel_path"

install -d -m 0700 -o root -g root /var/lib/waygate /var/lib/waygate/keys /run/waygate
install -m 0644 -o root -g root "$INSTALL_DIR/deploy/waygate.service" "$SERVICE_PATH"
install -m 0644 -o root -g root "$INSTALL_DIR/deploy/waygate.tmpfiles.conf" "$TMPFILES_PATH"
systemd-tmpfiles --create "$TMPFILES_PATH"

env_tmp="$(mktemp /etc/.waygate.env.XXXXXX)"
chmod 600 "$env_tmp"
{
  printf 'WG_INTERFACE=%s\n' "$WG_INTERFACE"
  printf 'WG_PORT=%s\n' "$WG_PORT"
  printf 'WG_SERVER_HOST=%s\n' "$WG_SERVER_HOST"
  printf 'WG_SERVER_NET=%s\n' "$WG_SERVER_NET"
  printf 'WG_DEFAULT_DNS=%s\n' "$WG_DEFAULT_DNS"
  printf 'API_AUTH_TOKEN=%s\n' "$API_AUTH_TOKEN"
  printf 'API_HOST=%s\n' "$API_HOST"
  printf 'API_PORT=%s\n' "$API_PORT"
  printf 'WG_PERSISTENT_KEEPALIVE=%s\n' "$WG_PERSISTENT_KEEPALIVE"
  [[ -n "$WG_OUTBOUND_INTERFACE" ]] && printf 'WG_OUTBOUND_INTERFACE=%s\n' "$WG_OUTBOUND_INTERFACE"
  [[ -n "$API_PUBLIC_BASE_URL" ]] && printf 'API_PUBLIC_BASE_URL=%s\n' "$API_PUBLIC_BASE_URL"
  printf 'ALLOW_INSECURE_HTTP=%s\n' "$ALLOW_INSECURE_HTTP"
  printf 'API_ALLOWED_CIDRS=%s\n' "$API_ALLOWED_CIDRS"
  printf 'API_DOCS_ENABLED=%s\n' "$API_DOCS_ENABLED"
} > "$env_tmp"
chown root:root "$env_tmp"
mv -f -- "$env_tmp" "$ENV_DEST"

systemctl daemon-reload
if ((NO_START == 0)); then
  systemctl enable --now "$APP_NAME.service"
  healthy=0
  for _ in {1..90}; do
    if curl --fail --silent --show-error --max-time 2 "http://127.0.0.1:${API_PORT}/healthz" >/dev/null 2>&1; then
      healthy=1
      break
    fi
    sleep 1
  done
  if ((healthy == 0)); then
    echo "Service did not become healthy within 90 seconds" >&2
    systemctl --no-pager --full status "$APP_NAME.service" >&2 || true
    exit 1
  fi
fi

if ((NO_START == 0)) && [[ -d /opt/afterglow-wg-agent ]]; then
  rm -rf -- /opt/afterglow-wg-agent
fi
printf 'installed=%s\nservice=%s\nendpoint=%s:%s\n' "$INSTALL_DIR" "$APP_NAME.service" "$WG_SERVER_HOST" "$WG_PORT"
