---
- name: Include Waygate image precheck tasks
  ansible.builtin.include_tasks: image_precheck.yml

- name: Pull | Pull Waygate images
  become: true
  community.docker.docker_image:
    name: "{{ item.value.image }}"
    source: pull
    force_source: true
  no_log: true
  loop: "{{ waygate_services | dict2items }}"
  when:
    - inventory_hostname in groups['waygate']
    - item.value.enabled | bool
    - not (waygate_source_mode | default(false) | bool)
