---
- name: Include precheck tasks
  ansible.builtin.include_tasks: precheck.yml

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml

- name: Include start tasks
  ansible.builtin.include_tasks: start.yml
