---
- name: Include pull tasks
  ansible.builtin.include_tasks: pull.yml

- name: Include bootstrap service tasks
  ansible.builtin.include_tasks: bootstrap_service.yml

- name: Include start tasks
  ansible.builtin.include_tasks: start.yml
